openapi: "3.0.0"
info:
  title: "Resume text analysis API"
  version: "1.0.0"
  description: "API for resume text analysis on whether the text contains substantive information."

servers:
  - url: "http://127.0.0.1:8000"

paths:
  /resume_analysis/predict:
    get:
      summary: "Returns prediction on whether the text contains substantive information to the 'ответы модели' field in the True Tabs table."
      description: "Predict whether the text contains substantive information."
      operationId: "resume_analysis"
      responses:
        200:
          description: "Returns the prediction on whether the text contains substantive information to the 'ответы модели' field in the True Tabs table."
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  prediction:
                    type: "string"
                    example: "Success."
        400:
          description: "Invalid request with non-string input."
